# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-29 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_transactiontable_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiontable',
            old_name='time',
            new_name='trnDateTime',
        ),
    ]
