# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20170129_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('IND', 'India'), ('USA', 'USA')], default='USA', max_length=3),
        ),
    ]
